# Generated by Django 6.0.2 on 2026-02-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الرتبة')),
                ('default_weekly_quota', models.FloatField(default=0.0, verbose_name='الحصة الأسبوعية الافتراضية')),
                ('default_monthly_quota', models.FloatField(default=0.0, verbose_name='الحصة الشهرية الافتراضية')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الورشة')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('military_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم العسكري')),
                ('weekly_quota_override', models.FloatField(blank=True, null=True, verbose_name='تجاوز الحصة الأسبوعية')),
                ('monthly_quota_override', models.FloatField(blank=True, null=True, verbose_name='تجاوز الحصة الشهرية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='trans_maint.militaryrank', verbose_name='الرتبة')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('vehicle_type', models.CharField(choices=[('company', 'ملكية المؤسسة'), ('private', 'ملك خاص')], max_length=20, verbose_name='نوع الملكية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة')], default='active', max_length=20, verbose_name='الحالة')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to='trans_maint.employee', verbose_name='المالك (إذا كان خاصاً)')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(max_length=100, verbose_name='نوع الرحلة')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='المنطقة/الجهة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ ووقت البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت العودة')),
                ('fuel_quota_granted', models.FloatField(default=0.0, verbose_name='الكمية الممنوحة للرحلة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trans_maint.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trans_maint.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='الكمية')),
                ('transaction_type', models.CharField(choices=[('issue', 'صرف'), ('addition', 'إضافة')], default='issue', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans_maint.employee', verbose_name='الموظف المستلم')),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transaction', to='trans_maint.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans_maint.vehicle', verbose_name='المركبة')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occurred', models.DateTimeField(verbose_name='تاريخ وقوع الحادث')),
                ('description', models.TextField(verbose_name='وصف الحادث')),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الإصلاح')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق')], default='open', max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans_maint.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب الصيانة')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('completed', 'مكتمل')], default='pending', max_length=20)),
                ('accident_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_repairs', to='trans_maint.accident')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans_maint.vehicle')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans_maint.workshop')),
            ],
        ),
    ]
