# Generated by Django 6.0.2 on 2026-02-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_maint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trans_maint.trip'),
        ),
    ]
