# Generated by Django 6.0.2 on 2026-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_maint', '0002_accident_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة'), ('under_repair', 'تحت الصيانة')], default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
