# Generated by Django 6.0.2 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_maint', '0003_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='date_completed',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='damage_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='تكلفة الإصلاح'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date_occurred',
            field=models.DateTimeField(db_index=True, verbose_name='تاريخ وقوع الحادث'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date_reported',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإبلاغ'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المعالجة'), ('completed', 'مكتمل')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(db_index=True, verbose_name='تاريخ ووقت البدء'),
        ),
    ]
